In [1]:
from transformers import (RobertaConfig,
                          RobertaForSequenceClassification,
                          RobertaTokenizer,
                          AdamW,
                          get_linear_schedule_with_warmup)
import torch
import pytorch_lightning as pl
from torch.optim import lr_scheduler
from torch import nn
import numpy as np

In [2]:
roberta = RobertaForSequenceClassification.from_pretrained('roberta-base')

Some weights of the model checkpoint at roberta-base were not used when initializing RobertaForSequenceClassification: ['lm_head.bias', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.decoder.weight', 'roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.weight', 'classifie

In [17]:
import Refactored_Baseline
import importlib
importlib.reload(Refactored_Baseline)

<module 'Refactored_Baseline' from '/home/jupyter/moral_stories/Refactored_Baseline.py'>

In [ ]:
!pip install sacrerouge

In [45]:
importlib.reload(Refactored_Baseline)
model = Refactored_Baseline.Baseline_Model(roberta, lr = .01)

In [5]:
from moral_dataset import *

#moral_processor = utils.MoralStoriesProcessor()
print(DatasetType.TRAIN.value)
#the_dataset = MoralStoryDataset("/Users/garbar/Downloads/moral_stories_datasets/classification/action+context/lexical_bias","train")
#training_data = moral_processor.get_train_examples("/Users/garbar/Downloads/moral_stories_datasets/classification/action+context/lexical_bias")
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
path = "/home/dataset/moral_stories_datasets/classification/action+context/lexical_bias"
datatype = DatasetType.TEST
modeltype = ModelNames.ROBERTA
tasktype = TaskTypes.ACTION_CONTEXT_CLS
the_moral_story = MoralStoryClassifyDataset(path,dataset_type = DatasetType.TEST,tokenizer=tokenizer,model_name=modeltype,tasktype=tasktype)

temp = (the_moral_story._process_data(the_moral_story._moral_story_data[0:10]))
print("OK")

train
OK


In [6]:
the_moral_story.process_data(start_index = 0, stop_index = 28)

In [7]:
some_value = next(iter(the_moral_story))

In [8]:
len(some_value['attention_mask'])

72

In [9]:
print(the_moral_story._tokenized_data[1].input_ids)

[3, 243, 18, 1099, 7, 28, 350, 7337, 8, 3874, 82, 62, 4, 34057, 13356, 62, 182, 419, 42, 662, 4, 894, 1072, 7, 146, 103, 7080, 4, 3, 3, 34057, 117, 354, 5846, 14225, 29, 10, 319, 9, 26520, 8, 31592, 77, 442, 39, 7080, 4, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [10]:
print(some_value['input_ids'][0])

tensor(3)


In [7]:
from torch.utils.data import random_split, DataLoader
data_loader = DataLoader(the_moral_story, batch_size=2, shuffle=False,num_workers=4)

In [46]:
trainer = pl.Trainer(min_epochs = 1, max_epochs = 2, checkpoint_callback = False,gpus=1)

GPU available: True, used: True
TPU available: False, using: 0 TPU cores


In [47]:
trainer.fit(model, data_loader)

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type                             | Params
-----------------------------------------------------------
0 | model | RobertaForSequenceClassification | 124 M 
-----------------------------------------------------------
124 M     Trainable params
0         Non-trainable params
124 M     Total params
498.589   Total estimated model params size (MB)


KILL ME pleafewfwese
tensor([[0.3440, 0.6560],
        [0.3648, 0.6352],
        [0.7292, 0.2708],
        [0.7244, 0.2756],
        [0.7275, 0.2725],
        [0.7259, 0.2741],
        [0.6547, 0.3453],
        [0.5432, 0.4568],
        [0.2999, 0.7001],
        [0.2819, 0.7181],
        [0.2768, 0.7232],
        [0.2856, 0.7144],
        [0.2888, 0.7112],
        [0.2886, 0.7114],
        [0.3957, 0.6043],
        [0.4039, 0.5961],
        [0.6336, 0.3664],
        [0.6569, 0.3431],
        [0.7240, 0.2760],
        [0.7173, 0.2827],
        [0.7134, 0.2866],
        [0.6928, 0.3072],
        [0.6877, 0.3123],
        [0.7133, 0.2867],
        [0.4286, 0.5714],
        [0.4078, 0.5922],
        [0.3355, 0.6645],
        [0.2977, 0.7023]])
tensor([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
        1, 0, 1, 0])
<class 'torch.Tensor'>
<class 'torch.Tensor'>
KILL ME pleafewfwese
tensor([[0.2943, 0.7057],
        [0.3219, 0.6781],
        [0.4925, 0.5075],
    

1

In [14]:
model.forward(next(iter(data_loader)))

Hi, Michael!


(tensor(0.5275, grad_fn=<NllLossBackward>),
 tensor([[-0.5396,  0.5161],
         [-0.1993, -0.0767]], grad_fn=<AddmmBackward>))

In [ ]:
print("HELLO")